Accounts/urls.py
from django.urls import path
from .  import views


app_name='accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

Articles/urls.py
from unicodedata import name
from django.urls import path
from django.urls.conf import re_path
from . import views
from .views import edit_article

app_name = 'particular'
urlpatterns = [
    path('',views.artyy,name="articles"),
    path('create',views.create_article,name='create'),
    path("<slug:slug>/",views.article_detail,name="detail"),
    path("edit/<slug:slug>", edit_article.as_view() ,name='edit'),
    path("log", views.log_view,name='log'),
]

Assesment/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from .  import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'mainslatt'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('assess/', include('ass1.urls')),
    path('',views.home,name='home'),
    path('articles/',include('Articles.urls')),
    path('accounts/',include('Accounts.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ass1/urls.py
from django.urls import path
from ass1 import views

urlpatterns = [
    path("",views.signup,name='signup'),
    path("<str:slug>/",views.customers),
]

Accounts/models.py
from django.db import models

# Create your models here.

Articles/models.py
from logging import PlaceHolder
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    thumbnail = models.ImageField(default='default.png',blank=True)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(User,default=None,on_delete=CASCADE )


    def get_absolute_url(self):
        return f'/articles/'

    def __str__(self):
        return self.title
    def slim(self):
        return self.body[:50]+".........."



    

ass1/models.py
from typing import Match
from django.db import models

# Create your models here.
class Member(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username =models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    

    def __str__(self):
        return self.email+" : "+self.username 

Articles/forms.py
from tkinter import Widget
from django import forms
from .models import Articles

class CreateArticle(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ['title','slug','body','thumbnail']
        widgets = {
            'title':forms.TextInput(attrs={'placeholder':'My New Article'}),
            'slug':forms.TextInput(attrs={'placeholder':'my-new-article'}),
            'body':forms.Textarea(attrs={'placeholder':'Once upon a time in .......'})

        }

class EditArticle(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ['title','slug','body','thumbnail']
        

ass1/forms.py
from django import forms
from django.db.models.base import Model
from django.forms import fields, widgets
from ass1.models import Member


class Reg(forms.ModelForm):
    class Meta:
        model = Member
        exclude = ['balance']
        widgets = {
            'password': forms.PasswordInput(),
            
        }

Accounts/views.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout

#from django.http import HttpResponse


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('particular:articles')
    else:    
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'ferm':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('particular:articles')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('particular:articles')

Articles/views.py
from gc import get_objects
from multiprocessing import context
from pyexpat import model
from re import template
from django.http.response import HttpResponse
from django.shortcuts import redirect, render,get_object_or_404
from .models import Articles
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import CreateArticle, EditArticle 
from django.views.generic import UpdateView


# Create your views here.
def artyy(request):
    instance = Articles.objects.all().order_by('date')
    dictionary = {'Articles':instance}
    return render(request,'articles.html',context=dictionary)



def article_detail(request,slug):
    article = Articles.objects.get(slug=slug)
    dictionary = {'art':article}
    return render(request,'articles/article_detail.html',dictionary)



@login_required(login_url="/accounts/login/")
def create_article(request):
    if request.method == 'POST':
        form = CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            #save form
            x = form.save(commit=False)
            x.author = request.user
            x.save()
            return redirect('particular:articles')
    else:
        form = CreateArticle()
    return render(request,'articles/create_article.html',{'form':form})


def edit_article(request,slug):
    article = Articles.objects.get(slug=slug)
    if request.method == 'POST':
        form = EditArticle(request.POST,instance=article)
        if form.is_valid():
            form.save()
            return redirect('particular:articles')
    else:
        form = EditArticle(article,slug)
    print(article.date)
    return render(request,'articles/edit_article.html',context={'form':form})


class edit_article(UpdateView):
    model = Articles
    template_name = 'articles/edit_article.html' 
    fields = ['title','body']

def log_view(request,slug):
    article = Articles.objects.get(slug=slug)


Assesment/views.py
from django.shortcuts import render

def home(request):
    return render(request,'homepage.html')

ass1/views.py
from django.shortcuts import render
from ass1.forms import Reg
from ass1.models import Member
# Create your views here.
def signup(request):
    formal = Reg()
    if request.method=="POST":
        formal = Reg(request.POST)
        if formal.is_valid():
            formal = formal.save(commit=True)
            print("Sign-Up Complete")
            print("Welcome ")
            return reindex(request)
            

    return render(request,'forms.html',{'form':formal})

def reindex(request):
    return render(request,'homepage.html')


def customers(request, slug):
    customer = Member.objects.get(id=slug)
    return render(request,'customer.html',{'customer':customer})

templates/accounts/login.html
{% extends 'base_layout.html'%}


{% block madden %}
<style>
h1{  
    color: aquamarine;
}
</style>
{% endblock %}

{% block content%}
<h1>Login</h1>
<br>
<form action="/accounts/login/" method="post" style="font-size: 1.5rem;">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    
    <button style="display: inline-block;
    font-family: 'Ubuntu';
        padding: 0.2rem 1.25rem;
        border-radius: 10rem;
        color:black;
        background-color: burlywood;
        text-transform: uppercase;
        font-size: 0.8rem;
        letter-spacing: 0.15rem;
        transition: all 0.3s;
        position: relative;
        overflow: hidden;
        z-index: 1;">Log-in</button>

</form>
{% endblock %}

templates/accounts/signup.html
{% extends 'base_layout.html'%}


{% block madden %}
<style>
.tinker{  
    color:burlywood;
    text-align: center;
}
img{
    align-items: center;
}
</style>
{% endblock %}

{% block content%}
<h2 class="tinker">Sign-up</h2>
<form style="list-style-type: none;" class='tinker' action='/accounts/signup/' method="post">
    {% csrf_token %}
    {{ ferm.as_p}}
    <button type="submit">Sign-up</button>

</form>
{% endblock %}

templates/articles.html
{% extends 'base_layout.html'%}

{% block madden %}
    <title>Articles</title>
    <style>
        .main{
        text-align: center;
        vertical-align: super;
        }
        a{
            color: lightgreen;
            text-decoration: none;
        }
        a:hover{
            color: aquamarine;
        }
    </style>
{% endblock %}

{% block content %}
    
    <div class='Articles container' style='padding-left:20px'>
        {% if Articles %}
            {% for art in Articles %}
                <h1 class="title"><a href="{% url 'particular:detail' slug=art.slug %}">{{art.title}}</a></h1>
                <h3 style="padding-top: 10px;">by <a href="">{{art.author}}</a></h3>
                <p>{{art.slim}}</p>
                <p>{{art.date}} <small><a href="{% url 'particular:log' %}">Edited</a></small></p>
                <br>
                <hr style="color:cadetblue">
            {% endfor %}

        {% endif %}
    </div>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block madden %}
    <style>
        .main{
            text-align: center;
        }
        h1{
            color: burlywood;
        }
    </style>

{% endblock %}

{% block content %}

{% if request.user == art.author %}
    <p>
        {% if art %}
        <a href="{% url 'particular:edit' slug=art.slug %}">
            Edit article
        </a>
        {% endif %}
    </p>
 

{% endif %}
<small><a href="{% url 'particular:articles' %}"><button style="display: inline-block;
font-family: 'Ubuntu';
    padding: 0.75rem 1.25rem;
    border-radius: 10rem;
    color:black;
    background-color: burlywood;
    text-transform: uppercase;
    font-size: 0.8rem;
    letter-spacing: 0.15rem;
    transition: all 0.3s;
    position: relative;
    overflow: hidden;
    z-index: 1;">Back</button></a></small>
<div style="padding-left: 20px; text-align: center;" class="articless">
    
    <h1>{{art.title}}</h1>

    <small ><h3 style="padding-top: 10px; padding-bottom: 5px;">by <a href=""></a>{{art.author}}</a></h3></small>
    <img src="{{ art.thumbnail.url }}" alt="thumbnail" style="width: 900px;height: 400px;">
    <p>{{art.body}}</p>
    <p>{{art.date}}</p>
</div>


{% endblock %}

templates/articles/create_article.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Add Article :) </h1>

<form class="site-form" action="{% url 'particular:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create">
</form>




{% endblock %}

templates/articles/edit_article.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Edit Your Article :) </h1>

<form class="site-form" action="{% url 'particular:articles' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Edit">
</form>




{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'slatt.css' %}">

    {% block madden %}
    {% endblock %}
    
</head>
<body>
    <div class="wrapper">
        <div class="main container">
            <h2 style='text-align: left; padding-left: 80px; padding-top: 20px;'id="home"><a href="{% url 'home' %}">HOME</a></h2>
            <br>
            <h1 style="text-align: left; padding-left: 10px;" ><a href="{% url 'particular:articles' %}"><img src="{% static 'logo.png' %}" alt="logo"></a></h1>
            <nav>
                <ul style="list-style-type: none;">
                    {% if user.is_authenticated %}
                        <li>  <form class="logout-link" action="{% url 'particular:create' %}" method="get">
                            {% csrf_token %}            
                            <button type="submit" style="display: inline-block;
                            font-family: 'Ubuntu';
                                padding: 0.75rem 1.25rem;
                                border-radius: 10rem;
                                color:black;
                                background-color: burlywood;
                                text-transform: uppercase;
                                font-size: 0.8rem;
                                letter-spacing: 0.15rem;
                                transition: all 0.3s;
                                position: relative;
                                overflow: hidden;
                                z-index: 1;">CREATE NEW ARTICLE</button>
                        </form></li>
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}            
                                <button type="submit" style="display: inline-block;
                                font-family: 'Ubuntu';
                                    padding: 0.75rem 1.25rem;
                                    border-radius: 10rem;
                                    color:black;
                                    background-color:burlywood;
                                    text-transform: uppercase;
                                    font-size: 0.8rem;
                                    letter-spacing: 0.15rem;
                                    transition: all 0.3s;
                                    position: relative;
                                    overflow: hidden;
                                    z-index: 1;">Log-out</button>
                            </form>
                        </li>
                    {% else %}
                    <div style="padding-right: 20px;">
                        <li style="text-align: right;"><a href="{% url 'accounts:login' %}"><button style="display: inline-block;
                            font-family: 'Ubuntu';
                                padding: 0.75rem 1.25rem;
                                border-radius: 10rem;
                                color:black;
                                background-color: burlywood;
                                text-transform: uppercase;
                                font-size: 0.8rem;
                                letter-spacing: 0.15rem;
                                transition: all 0.3s;
                                position: relative;
                                overflow: hidden;
                                z-index: 1;"> LOG IN </button></a></li>
                        <br>
                       <li style="text-align: right;"><a href="{% url 'accounts:signup' %}"><button style="display: inline-block;
                        font-family: 'Ubuntu';
                            padding: 0.75rem 1.25rem;
                            border-radius: 10rem;
                            color:black;
                            background-color:burlywood;
                            text-transform: uppercase;
                            font-size: 0.8rem;
                            letter-spacing: 0.15rem;
                            transition: all 0.3s;
                            position: relative;
                            overflow: hidden;
                            z-index: 1;"> SIGN-UP </button></a></li>
                    </div>
                    {% endif %}
                </ul>
            </nav>
        </div>  
        <br>
        <br>
        <div class="container">
            {% block content %}
            {% endblock %}
    
        </div>
    </div>
</body>
</html>

templates/customer.html
{% extends 'base_layout.html' %}


{% block content %}
<p>{{customer}}</p>
<p>your balance is ${{balance}}</p>
{% endblock %}


templates/forms.html
{% extends 'base_layout.html' %}
{% block madden %}
    <title>
        Sign-up
    </title>
    <style>
        form{
            border: black;
            border-width: 50px;
            background-color: rgb(8, 31, 31);
            padding: 40px;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="sign-up" id="btn">
        </form>

    </div>

{% endblock %}

templates/homepage.html
{% extends 'base_layout.html' %}

{% block madden %}
    <title>Home</title>
    <style>
        a{
            color: lightgreen;
            text-decoration: none;
        }
        a:hover{
            color: aquamarine
        }
        .slatt{
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
<div class="slatt">
    <h1 id="header-intro" style="font-family: italics; font-size: 10em; padding-right: 10px; padding-left: 10px;"><a href=""><i> Djangonautic </i> </a></h1>
    <br>
    <br>
 
</div>
{% endblock %}

templates/log.html
{% extends base_layout %}

{%  block content %}

<div class="date-log">

    {% if photo %}
        {% for x in photo %}
            <h3>{{x}}</h3>    
        {% endfor %}
    {% endif %}

</div>


{% endblock %}